services:

  # ==========================================
  # 1. Databases & Shared Infrastructure
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: shared_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frc_network

  redis:
    image: redis:7-alpine
    container_name: shared_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - frc_network

  neo4j:
    image: neo4j:5-community
    container_name: shared_neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/12345678
    volumes:
      - neo4j_data:/data
    networks:
      - frc_network

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: shared_elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - frc_network


  # ==========================================
  # 2. Fashion Community App (Backend) - (Frontend)
  # ==========================================
  frc-community-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fashion_community_backend
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - postgres
      - redis
      - neo4j
      - elasticsearch
    ports:
      - "4000:3000" 
    networks:
      - frc_network

  fashion-community-frontend:
    build:
      context: ../fashion-community-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.fashionretailclub.com
    container_name: fashion_community_frontend
    restart: unless-stopped
    env_file:
      - ../fashion-community-frontend/.env.production
    depends_on:
      - frc-community-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - frc_network


  # ==========================================
  # 3. Future Apps (LMS, Events) 
  # ==========================================
  # fashion-lms-backend:
  #   ...
  # fashion-events-frontend:
  #   ...


volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  elasticsearch_data:

networks:
  frc_network:
    driver: bridge









